package com.star.sud.model;
// Generated Aug 30, 2019 10:15:15 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TNtfnChnType generated by hbm2java
 */
@Entity
@Table(name = "T_NTFN_CHN_TYPE", catalog = "notification")
public class TNtfnChnType implements java.io.Serializable {

	// Static Attributes
	//////////////////////
	private static final long serialVersionUID = 2460587715829264487L;

	// Attributes
	/////////////////
	private String nchntypeId;
	private int nchntypeSeq;
	private String nchntypeDesc;
	private Set<TNtfnTemplate> TNtfnTemplates = new HashSet<TNtfnTemplate>(0);
	private Set<TNtfnDevice> TNtfnDevices = new HashSet<TNtfnDevice>(0);

	// Constructors
	//////////////////
	public TNtfnChnType() {
	}

	/**
	 * @param nchntypeId
	 * @param nchntypeSeq
	 * @param nchntypeDesc
	 * @param nchntypeStatus
	 */
	public TNtfnChnType(String nchntypeId, int nchntypeSeq, String nchntypeDesc) {
		this.nchntypeId = nchntypeId;
		this.nchntypeSeq = nchntypeSeq;
		this.nchntypeDesc = nchntypeDesc;
	}

	/**
	 * @param nchntypeId
	 * @param nchntypeSeq
	 * @param nchntypeDesc
	 * @param nchntypeStatus
	 * @param nchntypeUidCreate
	 * @param nchntypeDtCreate
	 * @param nchntypeUidLupd
	 * @param nchntypeDtLupd
	 * @param TNtfnTemplates
	 * @param TNtfnDevices
	 */
	public TNtfnChnType(String nchntypeId, int nchntypeSeq, String nchntypeDesc, Set<TNtfnTemplate> TNtfnTemplates,
			Set<TNtfnDevice> TNtfnDevices) {
		this.nchntypeId = nchntypeId;
		this.nchntypeSeq = nchntypeSeq;
		this.nchntypeDesc = nchntypeDesc;
		this.TNtfnTemplates = TNtfnTemplates;
		this.TNtfnDevices = TNtfnDevices;
	}

	// Properties
	////////////////
	@Id
	@Column(name = "NCHNTYPE_ID", unique = true, nullable = false, length = 35)
	public String getNchntypeId() {
		return this.nchntypeId;
	}

	public void setNchntypeId(String nchntypeId) {
		this.nchntypeId = nchntypeId;
	}

	@Column(name = "NCHNTYPE_SEQ", nullable = false)
	public int getNchntypeSeq() {
		return this.nchntypeSeq;
	}

	public void setNchntypeSeq(int nchntypeSeq) {
		this.nchntypeSeq = nchntypeSeq;
	}

	@Column(name = "NCHNTYPE_DESC", nullable = false, length = 1024)
	public String getNchntypeDesc() {
		return this.nchntypeDesc;
	}

	public void setNchntypeDesc(String nchntypeDesc) {
		this.nchntypeDesc = nchntypeDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TNtfnChnType")
	public Set<TNtfnTemplate> getTNtfnTemplates() {
		return this.TNtfnTemplates;
	}

	public void setTNtfnTemplates(Set<TNtfnTemplate> TNtfnTemplates) {
		this.TNtfnTemplates = TNtfnTemplates;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TNtfnChnType")
	public Set<TNtfnDevice> getTNtfnDevices() {
		return this.TNtfnDevices;
	}

	public void setTNtfnDevices(Set<TNtfnDevice> TNtfnDevices) {
		this.TNtfnDevices = TNtfnDevices;
	}

}
