package com.star.sud.model;
// Generated Aug 30, 2019 10:15:15 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TNtfnTemplate generated by hbm2java
 */
@Entity
@Table(name = "T_NTFN_TEMPLATE", catalog = "notification")
public class TNtfnTemplate implements java.io.Serializable {

	// Static Attributes
	////////////////////////
	private static final long serialVersionUID = 5915186536606225222L;

	// Attributes
	/////////////////
	private String ntplId;
	private TNtfnChnType TNtfnChnType;
	private TNtfnCntType TNtfnCntType;
	private String ntplSubject;
	private String ntplTempalte;
	private int ntplSeq;
	private String ntplDesc;

	public TNtfnTemplate() {
	}

	/**
	 * @param ntplId
	 * @param TNtfnChnType
	 * @param TNtfnCntType
	 * @param ntplSeq
	 * @param ntplDesc
	 * @param ntplStatus
	 */
	public TNtfnTemplate(String ntplId, TNtfnChnType TNtfnChnType, TNtfnCntType TNtfnCntType, int ntplSeq,
			String ntplDesc) {
		this.ntplId = ntplId;
		this.TNtfnChnType = TNtfnChnType;
		this.TNtfnCntType = TNtfnCntType;
		this.ntplSeq = ntplSeq;
		this.ntplDesc = ntplDesc;
	}

	/**
	 * @param ntplId
	 * @param TNtfnChnType
	 * @param TNtfnCntType
	 * @param ntplSubject
	 * @param ntplTempalte
	 * @param ntplSeq
	 * @param ntplDesc
	 * @param ntplStatus
	 * @param ntplUidCreate
	 * @param ntplDtCreate
	 * @param ntplUidLupd
	 * @param ntplDtLupd
	 */
	public TNtfnTemplate(String ntplId, TNtfnChnType TNtfnChnType, TNtfnCntType TNtfnCntType, String ntplSubject,
			String ntplTempalte, int ntplSeq, String ntplDesc) {
		this.ntplId = ntplId;
		this.TNtfnChnType = TNtfnChnType;
		this.TNtfnCntType = TNtfnCntType;
		this.ntplSubject = ntplSubject;
		this.ntplTempalte = ntplTempalte;
		this.ntplSeq = ntplSeq;
		this.ntplDesc = ntplDesc;
	}

	// Properties
	////////////////
	@Id

	@Column(name = "NTPL_ID", unique = true, nullable = false, length = 35)
	public String getNtplId() {
		return this.ntplId;
	}

	public void setNtplId(String ntplId) {
		this.ntplId = ntplId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NTPL_CHANNEL_TYPE", nullable = false)
	public TNtfnChnType getTNtfnChnType() {
		return this.TNtfnChnType;
	}

	public void setTNtfnChnType(TNtfnChnType TNtfnChnType) {
		this.TNtfnChnType = TNtfnChnType;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NTPL_CONTENT_TYPE", nullable = false)
	public TNtfnCntType getTNtfnCntType() {
		return this.TNtfnCntType;
	}

	public void setTNtfnCntType(TNtfnCntType TNtfnCntType) {
		this.TNtfnCntType = TNtfnCntType;
	}

	@Column(name = "NTPL_SUBJECT", length = 4096)
	public String getNtplSubject() {
		return this.ntplSubject;
	}

	public void setNtplSubject(String ntplSubject) {
		this.ntplSubject = ntplSubject;
	}

	@Column(name = "NTPL_TEMPALTE", length = 65535)
	public String getNtplTempalte() {
		return this.ntplTempalte;
	}

	public void setNtplTempalte(String ntplTempalte) {
		this.ntplTempalte = ntplTempalte;
	}

	@Column(name = "NTPL_SEQ", nullable = false)
	public int getNtplSeq() {
		return this.ntplSeq;
	}

	public void setNtplSeq(int ntplSeq) {
		this.ntplSeq = ntplSeq;
	}

	@Column(name = "NTPL_DESC", nullable = false, length = 1024)
	public String getNtplDesc() {
		return this.ntplDesc;
	}

	public void setNtplDesc(String ntplDesc) {
		this.ntplDesc = ntplDesc;
	}

}
