package com.star.sud.model;
// Generated Aug 30, 2019 10:15:15 PM by Hibernate Tools 5.2.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * TNtfnDevice generated by hbm2java
 */
@Entity
@Table(name = "T_NTFN_DEVICE", catalog = "notification")
public class TNtfnDevice implements java.io.Serializable {

	// Static Attributes
	///////////////////////
	private static final long serialVersionUID = -2149445220291634299L;

	// Attributes
	/////////////////
	private String ndevId;
	private TNtfnChnType TNtfnChnType;
	private String ndevConfig;
	private int ndevSeq;
	private String ndevDesc;

	// Constructors
	//////////////////
	public TNtfnDevice() {
	}

	/**
	 * @param ndevId
	 * @param TNtfnChnType
	 * @param ndevConfig
	 * @param ndevSeq
	 * @param ndevDesc
	 * @param ndevStatus
	 */
	public TNtfnDevice(String ndevId, TNtfnChnType TNtfnChnType, String ndevConfig, int ndevSeq, String ndevDesc) {
		this.ndevId = ndevId;
		this.TNtfnChnType = TNtfnChnType;
		this.ndevConfig = ndevConfig;
		this.ndevSeq = ndevSeq;
		this.ndevDesc = ndevDesc;
	}

	@Id

	@Column(name = "NDEV_ID", unique = true, nullable = false, length = 35)
	public String getNdevId() {
		return this.ndevId;
	}

	public void setNdevId(String ndevId) {
		this.ndevId = ndevId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "NDEV_CHANNEL_TYPE", nullable = false)
	public TNtfnChnType getTNtfnChnType() {
		return this.TNtfnChnType;
	}

	public void setTNtfnChnType(TNtfnChnType TNtfnChnType) {
		this.TNtfnChnType = TNtfnChnType;
	}

	@Column(name = "NDEV_CONFIG", nullable = false, length = 8192)
	public String getNdevConfig() {
		return this.ndevConfig;
	}

	public void setNdevConfig(String ndevConfig) {
		this.ndevConfig = ndevConfig;
	}

	@Column(name = "NDEV_SEQ", nullable = false)
	public int getNdevSeq() {
		return this.ndevSeq;
	}

	public void setNdevSeq(int ndevSeq) {
		this.ndevSeq = ndevSeq;
	}

	@Column(name = "NDEV_DESC", nullable = false, length = 1024)
	public String getNdevDesc() {
		return this.ndevDesc;
	}

	public void setNdevDesc(String ndevDesc) {
		this.ndevDesc = ndevDesc;
	}

}
