package com.star.sud.model;
// Generated Aug 30, 2019 10:15:15 PM by Hibernate Tools 5.2.1.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TNtfnCntType generated by hbm2java
 */
@Entity
@Table(name = "T_NTFN_CNT_TYPE", catalog = "notification")
public class TNtfnCntType implements java.io.Serializable {

	// Static Attributes
	//////////////////////
	private static final long serialVersionUID = 3658283032475241969L;

	// Attributes
	/////////////////
	private String ncnttypeId;
	private int ncnttypeSeq;
	private String ncnttypeDesc;
	private Set<TNtfnTemplate> TNtfnTemplates = new HashSet<TNtfnTemplate>(0);

	// Constructors
	/////////////////
	public TNtfnCntType() {
	}

	/**
	 * @param ncnttypeId
	 * @param ncnttypeSeq
	 * @param ncnttypeDesc
	 * @param ncnttypeStatus
	 */
	public TNtfnCntType(String ncnttypeId, int ncnttypeSeq, String ncnttypeDesc) {
		this.ncnttypeId = ncnttypeId;
		this.ncnttypeSeq = ncnttypeSeq;
		this.ncnttypeDesc = ncnttypeDesc;
	}

	/**
	 * @param ncnttypeId
	 * @param ncnttypeSeq
	 * @param ncnttypeDesc
	 * @param ncnttypeStatus
	 * @param ncnttypeUidCreate
	 * @param ncnttypeDtCreate
	 * @param ncnttypeUidLupd
	 * @param ncnttypeDtLupd
	 * @param TNtfnTemplates
	 */
	public TNtfnCntType(String ncnttypeId, int ncnttypeSeq, String ncnttypeDesc, Set<TNtfnTemplate> TNtfnTemplates) {
		this.ncnttypeId = ncnttypeId;
		this.ncnttypeSeq = ncnttypeSeq;
		this.ncnttypeDesc = ncnttypeDesc;
		this.TNtfnTemplates = TNtfnTemplates;
	}

	// Properties
	////////////////
	@Id
	@Column(name = "NCNTTYPE_ID", unique = true, nullable = false, length = 35)
	public String getNcnttypeId() {
		return this.ncnttypeId;
	}

	public void setNcnttypeId(String ncnttypeId) {
		this.ncnttypeId = ncnttypeId;
	}

	@Column(name = "NCNTTYPE_SEQ", nullable = false)
	public int getNcnttypeSeq() {
		return this.ncnttypeSeq;
	}

	public void setNcnttypeSeq(int ncnttypeSeq) {
		this.ncnttypeSeq = ncnttypeSeq;
	}

	@Column(name = "NCNTTYPE_DESC", nullable = false, length = 1024)
	public String getNcnttypeDesc() {
		return this.ncnttypeDesc;
	}

	public void setNcnttypeDesc(String ncnttypeDesc) {
		this.ncnttypeDesc = ncnttypeDesc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "TNtfnCntType")
	public Set<TNtfnTemplate> getTNtfnTemplates() {
		return this.TNtfnTemplates;
	}

	public void setTNtfnTemplates(Set<TNtfnTemplate> TNtfnTemplates) {
		this.TNtfnTemplates = TNtfnTemplates;
	}

}
